# Generated by Django 3.1.5 on 2021-01-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210117_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.IntegerField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=128, null=True)),
                ('comments', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='country_information',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nationality', models.CharField(max_length=128, null=True)),
                ('dailing_code', models.CharField(max_length=128, null=True)),
                ('country_name', models.CharField(max_length=128, null=True)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
            ],
        ),
    ]
