# Generated by Django 3.1.5 on 2021-01-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_country_information_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='testout',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
