# Generated by Django 3.1.5 on 2021-01-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210119_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='comments',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='comments',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
