# Generated by Django 3.1.5 on 2021-01-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210119_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescriptionTemplate',
            fields=[
                ('job_desc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description_title', models.CharField(max_length=255)),
                ('organisation_job_description', models.TextField(null=True)),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='section_template',
            fields=[
                ('section_id', models.IntegerField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=128, null=True)),
                ('section_desc', models.TextField(null=True)),
                ('display_order', models.IntegerField(null=True)),
                ('display_name', models.CharField(max_length=128)),
            ],
        ),
    ]
