# Generated by Django 3.1.5 on 2021-01-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_jobdescriptiontemplate_section_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_information',
            name='country_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobdescriptiontemplate',
            name='job_desc_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section_template',
            name='section_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testout',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
