# Generated by Django 3.1.5 on 2021-01-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_testout_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAuthority',
            fields=[
                ('issue_authority_id', models.IntegerField(primary_key=True, serialize=False)),
                ('authority_name', models.CharField(max_length=255, null=True)),
                ('acronym', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('licensing', models.BooleanField(default=False)),
                ('qualification', models.BooleanField(default=False)),
                ('issue_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country_information')),
            ],
        ),
        migrations.AlterField(
            model_name='testout',
            name='items',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='PqrHeader',
            fields=[
                ('pqr_header_id', models.AutoField(primary_key=True, serialize=False)),
                ('pqr_name', models.CharField(max_length=128, null=True)),
                ('issue_date', models.DateField(null=True)),
                ('version_no', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('comments', models.CharField(max_length=255, null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country_information')),
                ('issue_authority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.issueauthority')),
            ],
        ),
        migrations.CreateModel(
            name='PqrDetail',
            fields=[
                ('pqr_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('surgical', models.BooleanField(default=False, null=True)),
                ('min_years_exp', models.IntegerField(null=True)),
                ('min_years_exp_for_nationals', models.IntegerField(null=True)),
                ('specialist_registration_held', models.BooleanField(default=False, null=True)),
                ('specialist_reg_required_for_nationals', models.BooleanField(default=False, null=True)),
                ('specialist_registration_years', models.IntegerField(null=True)),
                ('check_equivalence', models.BooleanField(default=False, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('comments', models.CharField(max_length=255, null=True)),
                ('issue_authority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.issueauthority')),
                ('pqr_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pqrheader')),
            ],
        ),
    ]
