# Generated by Django 3.1.5 on 2021-01-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210121_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=128, null=True)),
                ('qualification_level', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('acronym', models.CharField(max_length=128, null=True)),
                ('english_translation', models.CharField(max_length=128, null=True)),
                ('specialist_registration_reqd', models.BooleanField(default=False, null=True)),
                ('by_exam', models.BooleanField(default=False)),
                ('course_duration_reqd', models.BooleanField(default=False, null=True)),
                ('comments', models.CharField(default=False, max_length=128, null=True)),
                ('allow_subject_input', models.BooleanField(default=False, null=True)),
                ('display_order', models.IntegerField(null=True)),
                ('equivalent_qualification', models.BooleanField(default=False, null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country_information')),
            ],
        ),
    ]
