# Generated by Django 3.1.5 on 2021-01-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_continent_country_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateLevel',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_level', models.CharField(max_length=128, null=True)),
                ('description', models.CharField(max_length=128, null=True)),
                ('seniority', models.IntegerField(null=True)),
                ('comments', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateType',
            fields=[
                ('candidate_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_type', models.CharField(max_length=128, null=True)),
                ('comments', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobdescriptiontemplate',
            name='desired_information',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiontemplate',
            name='essential_information',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiontemplate',
            name='organisation_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiontemplate',
            name='qualifications_required',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdescriptiontemplate',
            name='skills_required',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pqrdetail',
            name='dependent_pqr_detail_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pqrdetail'),
        ),
        migrations.AddField(
            model_name='pqrdetail',
            name='qual_country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country_information'),
        ),
        migrations.AddField(
            model_name='pqrdetail',
            name='qualification_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.qualification'),
        ),
        migrations.AlterField(
            model_name='jobdescriptiontemplate',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescriptiontemplate',
            name='description_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pqrdetail',
            name='issue_authority_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.issueauthority'),
        ),
        migrations.AlterField(
            model_name='pqrdetail',
            name='pqr_header_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pqrheader'),
        ),
        migrations.CreateModel(
            name='QualificationClassification',
            fields=[
                ('qualification_classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification_classification', models.CharField(max_length=128, null=True)),
                ('sort_level', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=128, null=True)),
                ('candidate_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.candidatetype')),
                ('level_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.candidatelevel')),
            ],
        ),
        migrations.AddField(
            model_name='candidatelevel',
            name='candidate_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.candidatetype'),
        ),
        migrations.AddField(
            model_name='candidatelevel',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country_information'),
        ),
        migrations.AddField(
            model_name='candidatelevel',
            name='issue_authority_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.issueauthority'),
        ),
        migrations.AddField(
            model_name='pqrdetail',
            name='candidate_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.candidatetype'),
        ),
        migrations.AddField(
            model_name='pqrdetail',
            name='level_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.candidatelevel'),
        ),
        migrations.AddField(
            model_name='pqrdetail',
            name='qualification_classification_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.qualificationclassification'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_classification_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.qualificationclassification'),
        ),
    ]
