# Generated by Django 3.1.5 on 2021-01-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210122_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issueauthority',
            old_name='issue_country_id',
            new_name='country_id',
        ),
    ]
