# Generated by Django 3.1.5 on 2021-01-23 10:44

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210123_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrdetail',
            name='candidate_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_type_new', to='main.candidatetype'),
        ),
        migrations.AlterField(
            model_name='pqrdetail',
            name='level_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='candidate_type_id', chained_model_field='candidate_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_level_new', to='main.candidatelevel'),
        ),
    ]
