# Generated by Django 3.1.5 on 2021-01-23 12:28

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210123_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrdetail',
            name='qualification_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='qualification_classification_id', chained_model_field='qualification_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification_new', to='main.qualification'),
        ),
    ]
