# Generated by Django 3.1.5 on 2021-01-23 12:34

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210123_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrdetail',
            name='issue_authority_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='qualification_id', chained_model_field='issue_country_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_authority_new', to='main.issueauthority'),
        ),
    ]
