# Generated by Django 3.1.5 on 2021-01-23 18:59

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210123_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='candidate_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.candidatetype'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='continent', chained_model_field='continent', on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
        migrations.AlterField(
            model_name='pqrdetail',
            name='issue_authority_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='qualification_id', chained_model_field='issue_country_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_authority_new', to='main.issueauthority'),
        ),
        migrations.AlterField(
            model_name='pqrdetail',
            name='level_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='candidate_type_id', chained_model_field='country_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_level_new', to='main.candidatelevel'),
        ),
        migrations.AlterField(
            model_name='pqrdetail',
            name='qualification_classification_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='qual_country_id', chained_model_field='candidate_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification_classification_new', to='main.qualificationclassification'),
        ),
        migrations.AlterField(
            model_name='pqrdetail',
            name='qualification_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='qualification_classification_id', chained_model_field='qualification_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification_new', to='main.qualification'),
        ),
    ]
