# Generated by Django 3.1.5 on 2021-01-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210123_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAuthorityCandidateType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.candidatetype')),
                ('issue_authority_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.issueauthority')),
            ],
        ),
        migrations.AddField(
            model_name='issueauthority',
            name='issue_authority_candidate_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.issueauthoritycandidatetype'),
        ),
    ]
