# Generated by Django 3.1.5 on 2021-01-25 09:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210124_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='testout',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), null=True, size=8),
        ),
        migrations.AlterField(
            model_name='pqrdetail',
            name='dependent_pqr_detail_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='pqr_header_id', chained_model_field='pqr_header_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pqr_header_new', to='main.pqrdetail'),
        ),
        migrations.AlterField(
            model_name='pqrdetail',
            name='issue_authority_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='qual_country_id', chained_model_field='issue_country_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_authority_new', to='main.issueauthority'),
        ),
        migrations.AlterField(
            model_name='pqrdetail',
            name='level_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='candidate_type_id', chained_model_field='candidate_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_level_new', to='main.candidatelevel'),
        ),
        migrations.AlterField(
            model_name='pqrdetail',
            name='qualification_classification_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='candidate_type_id', chained_model_field='candidate_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification_classification_new', to='main.qualificationclassification'),
        ),
    ]
